//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ASC {
            get {
                object obj = ResourceManager.GetObject("ASC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///    span#_error {
        ///        color: #E95E5E;
        ///        width: 100%;
        ///        left: auto;
        ///        right: auto;
        ///    }
        ///&lt;/style&gt;
        ///&lt;span id=&quot;_error&quot;&gt;    
        ///    §error_code§&lt;br /&gt;    
        ///    §error_message§&lt;br /&gt;
        ///    §error_submessage§
        ///&lt;/span&gt;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- AUTO-GENERATED §time:yyyy-MM-dd HH:mm:ss:ffffff§ --&gt;
        ///&lt;html lang=&quot;§lang_code§&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta name=&quot;§lang_name§&quot; content=&quot;§lang_code§&quot;/&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///        &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///        &lt;meta name=&quot;title&quot; content=&quot;§global_title§&quot;/&gt;
        ///        &lt;meta name=&quot;description&quot; content=&quot;§global_descr§&quot;/&gt;
        ///        &lt;meta name=&quot;robots&quot; content=&quot;all&quot;/&gt;
        ///        &lt;meta name=&quot;rating&quot; co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frame {
            get {
                return ResourceManager.GetString("frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */
        ///!function(a,b){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){&quot;use strict&quot;;var c=[],d=a.document,e=Object.getPrototypeOf,f=c.slice,g=c.concat,h=c.push,i=c.indexOf,j={},k=j.toString,l=j.hasOwnProperty,m=l.toString,n=m.call(Object), [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery311min {
            get {
                return ResourceManager.GetString("jquery311min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* AUTO-GENERATED §time:yyyy-MM-dd HH:mm:ss:ffffff§ */
        ///
        ///@import url(&apos;https://fonts.googleapis.com/css?family=UnifrakturCook:700&apos;);
        ///
        ///* {
        ///    font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///    font-size: 12pt;
        ///}
        ///
        ///body {
        ///    background-color: #222;
        ///    color: wheat;
        ///}
        ///
        ///#header,
        ///#footer {
        ///    background-color: #333;
        ///    z-index: 6000000;
        ///    position: fixed;
        ///    width: 100%;
        ///    right: 0px;
        ///    left: 0px;
        ///}
        ///
        ///#header {
        ///    border-bottom: 1px solid #999;
        ///    top: 0px;
        ///}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Unknown6656 {
            get {
                object obj = ResourceManager.GetObject("Unknown6656", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
